# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
# and modified by author

from PyQt5 import QtCore, QtGui, QtWidgets
from lang import Lang

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, lang=None):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 321)
        #self.texteditstyle = "QPlainTextEdit {background: #2b2b2b;border-style: inset; border-width: 1px; border-color: #258; border-radius: 10px;}"
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        #self.centralwidget.setStyleSheet("Background:  #222; color:  #aaa;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.peDir = QtWidgets.QPlainTextEdit(self.widget_2)
        self.peDir.setMinimumSize(QtCore.QSize(0, 28))
        self.peDir.setMaximumSize(QtCore.QSize(16777215, 24))
        #self.peDir.setStyleSheet(self.texteditstyle)
        self.peDir.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.peDir.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.peDir.setObjectName("peDir")
        self.horizontalLayout_2.addWidget(self.peDir)
        self.bBrowse = QtWidgets.QToolButton(self.widget_2)
        self.bBrowse.setMinimumSize(QtCore.QSize(30, 0))
        self.bBrowse.setObjectName("bBrowse")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/folder_103595.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bBrowse.setIcon(icon)
        self.horizontalLayout_2.addWidget(self.bBrowse)
        self.verticalLayout.addWidget(self.widget_2)
        self.bSet = QtWidgets.QToolButton(self.widget_2)
        self.bSet.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSet.setIcon(icon1)
        self.bSet.setAutoRaise(True)
        self.bSet.setObjectName("bSet")
        self.horizontalLayout_2.addWidget(self.bSet)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.peLink = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.peLink.setMaximumSize(QtCore.QSize(16777215, 180))
        #self.peLink.setStyleSheet(self.texteditstyle)
        self.peLink.setObjectName("peLink")
        self.verticalLayout.addWidget(self.peLink)
        self.lSize = QtWidgets.QLabel(self.centralwidget)
        self.lSize.setObjectName("lSize")
        self.verticalLayout.addWidget(self.lSize)
        self.hl_size = QtWidgets.QHBoxLayout()
        self.hl_size.setContentsMargins(-1, 0, -1, 0)
        self.hl_size.setObjectName("hl_size")
        self.b720 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b720.sizePolicy().hasHeightForWidth())
        self.b720.setSizePolicy(sizePolicy)
        self.b720.setCheckable(True)
        self.b720.setChecked(True)
        self.b720.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.b720.setAutoExclusive(True)
        self.b720.setObjectName("b720")
        self.hl_size.addWidget(self.b720)
        self.bMax = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bMax.sizePolicy().hasHeightForWidth())
        self.bMax.setSizePolicy(sizePolicy)
        self.bMax.setCheckable(True)
        self.bMax.setAutoExclusive(True)
        self.bMax.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.bMax.setObjectName("bMax")
        self.hl_size.addWidget(self.bMax)
        self.bFormats = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bFormats.sizePolicy().hasHeightForWidth())
        self.bFormats.setSizePolicy(sizePolicy)
        self.bFormats.setCheckable(True)
        self.bFormats.setAutoExclusive(True)
        self.bFormats.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.bFormats.setObjectName("bFormats")
        self.hl_size.addWidget(self.bFormats)
        self.verticalLayout.addLayout(self.hl_size)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 36))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bDownload = QtWidgets.QPushButton(self.widget)
        self.bDownload.setObjectName("bDownload")
        self.horizontalLayout.addWidget(self.bDownload)
        self.bPlay = QtWidgets.QPushButton(self.widget)
        self.bPlay.setObjectName("bPlay")
        #self.bPlay.setEnabled(False)
        self.horizontalLayout.addWidget(self.bPlay)
        self.verticalLayout.addWidget(self.widget)
        self.pb = QtWidgets.QProgressBar(self.centralwidget)
        self.pb.setMaximumSize(QtCore.QSize(16777215, 14))
        self.pb.setProperty("value", 0)
        self.pb.setObjectName("pb")
        self.verticalLayout.addWidget(self.pb)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.peLog = QtWidgets.QPlainTextEdit(self.centralwidget)
        #self.peLog.setStyleSheet(self.texteditstyle)
        self.peLog.setObjectName("peLog")
        self.peLog.setReadOnly(True)
        self.verticalLayout.addWidget(self.peLog)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow, lang)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, lang):
        if lang == None:
            lang = Lang()
        MainWindow.setWindowTitle(lang.tr("youtube_download"))
        self.label_3.setText(lang.tr("where_to_save"))
        self.bBrowse.setText("...")
        self.label.setText(lang.tr("links"))
        self.bDownload.setText(lang.tr("download"))
        self.bPlay.setText(lang.tr("play_downloading"))
        self.label_2.setText(lang.tr("log"))
        self.lSize.setText(lang.tr("size"))
        self.b720.setText("1280x720")
        self.bMax.setText(lang.tr("maximum"))
        self.bFormats.setText(lang.tr("show_formats"))

import images_rc

